### PR TITLE
Use yaml.parse to allow special YAML tags

### PR DESCRIPTION
**Pull request by adamchainz**
Ref #6.

### CODE REVIEW

**Comment by adamchainz** [comment]
Since there are no unit tests I did some manual testing to check that `yaml.parse` does indeed allow `!tags` but still throws the familiar parsing errors:

```py
In [1]: import yaml

In [2]: def lint(code):
   ...:     list(yaml.parse(code, Loader=yaml.BaseLoader))
   ...:

In [3]: lint('a')

In [4]: lint('!a foo')

In [5]: lint('Key: {{')
...
ParserError: while parsing a flow node
expected the node content, but found '<stream end>'
  in "<string>", line 1, column 8:
    Key: {{
           ^

In [6]: lint('}}')
...
ParserError: while parsing a block node
expected the node content, but found '}'
  in "<string>", line 1, column 1:
    }}
    ^

In [7]: lint('"a')
...
ScannerError: while scanning a quoted scalar
  in "<string>", line 1, column 1:
    "a
    ^
found unexpected end of stream
  in "<string>", line 1, column 3:
    "a
      ^
```

**Comment by adamchainz** [comment]
@NotSqrt bump

**Comment by adamchainz** [comment]
@NotSqrt bump

I don't want to have to figure out how to use a fork

**Comment by NotSqrt** [comment]
Ok, I finally took the time to check how it behaves when running into unsafe content (I used https://www.kevinlondon.com/2015/08/15/dangerous-python-functions-pt2.html as example), and multiple yaml documents in the same file, and it works

**Comment by adamchainz** [comment]
Thanks! 🎉

**Pull request merged**
